version: "3.7"
services:
  app:
    image: kooldev/node:16
    command: ["npx", "nodemon", "./src/app.js", "-L"]
    ports:
      - "${KOOL_APP_PORT:-5000}:5000"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
  #mongodb database
  mongo:
    image: mongo
    restart: always
    ports:
      - "${KOOL_DB_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${KOOL_ASUSER:-0}" #root
      MONGO_INITDB_ROOT_PASSWORD: "${UID:-0}" #example
    networks:
      - kool_local

networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
